server:
  port: 8082
spring:
  application:
    name: 'birthday-reminder-application'
  datasource:
    driverClassName: 'org.h2.Driver'
    url: 'jdbc:h2:mem:bdaydb'
    username: 'sa'
    password: 'password'
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    show-sql: false
    hibernate:
      ddl-auto: 'update'
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

logging:
  level:
    org.hibernate.SQL: 'DEBUG'